services:
  api:
    build:
      context: ./WeatherAppSolution/WeatherApp
    container_name: weather-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:8080
      - ConnectionStrings__DefaultConnection=Server=host.docker.internal,1433;Database=WeatherDb;User Id=sa;Password=Thapar@98;Encrypt=True;TrustServerCertificate=True;
    ports:
      - "7186:8080"
    restart: always

  frontend:
    build:
      context: ./weather-ui
    container_name: weather-ui
    depends_on:
      - api
    ports:
      - "4200:80"

volumes:
  sql_data: